### ISSUE TITLE
govtarget in Kent

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-load#38] opened 2016-02-11 16:48 UTC
The gov target scenario is coming out wrong, it seems never to be more than baseline and sometimes less - while should always be at least equal to baseline no. cyclists.

**Comment by Robinlovelace** [comment] 2016-02-21 08:44
Hi @AnnaGoodman1 thanks for spotting this. This was caused by incorrect code, possibly added accidentally but @nikolai-b here: https://github.com/npct/pct-shiny/blame/0c83ce79ce141caa0828e0a7a14e4fdf9f007d15/pct-shiny-funs.R#L41 (just for heads up Nikolai).

Fixed here so closing: https://github.com/npct/pct-shiny/commit/0c83ce79ce141caa0828e0a7a14e4fdf9f007d15

**Closed as completed by Robinlovelace** 2016-02-21 08:44 UTC
